Zapisywanie specjalizacji lekarzy
andrzejmaj/health_manager pull request #6
Opened 2017-07-21 17:31 UTC by WojciechKarpiel

https://jira.iisg.agh.edu.pl/browse/MEDCOM-6

2017-07-22 13:54 UTC, zalon525 requested changes
- brakuje updatowania doktorów (celowo?)
- zmienić nazwę metody DoctorController.savePatient -> DoctorController.saveDoctor

- czy specialization jako string zamiast id do osobnej tabeli to dobry pomysł? Przede wszystkim brak jakiejkolwiek walidacji - można tam wpisać cokolwiek

2017-07-22 16:16 UTC, WojciechKarpiel commented
>    brakuje updatowania doktorów (celowo?)
Bo nie jest to teraz potrzebne i nie umiem :P
>    zmienić nazwę metody DoctorController.savePatient -> DoctorController.saveDoctor
fial
>    czy specialization jako string zamiast id do osobnej tabeli to dobry pomysł? Przede wszystkim brak jakiejkolwiek walidacji - można tam wpisać cokolwiek
Dałem opakowanie na specjalizację. umiesz wymusić żeby
dodawanie drugiego lekarza z tą samą specjalizają nie dodawało nowej? (teraz dodałem unique constraint, w takiej sytuacji się wywali).

2017-07-22 23:17 UTC, zalon525 commented
Moja propozycja jest taka, żeby zrobić osobne API do dodawania specjalizacji. Przy dodawaniu lekarza nie dodajemy nowej specjalizacji tylko ustawiamy odpowiedni klucz obcy (czy też pole referencyjne w przypadku Javy). Czyli w DoctorDTO zostawałby sam klucz specjalizacji. Tylko teraz nie wiem, jak by to wyglądało na froncie. Wyobrażam sobie osobną zakładkę do tworzenia specjalizacji, a przy tworzeniu lekarza - dropdown ze specjalizacjami. Pytanie czy to jest lepsze... Jest z tym trochę zachodu, ale za to mamy gwarancję, że każdy lekarz ma jedną ze zdefiniowanych specjalizacji.

A jeśli chcesz przy zapisywaniu lekarza zapisywać automatycznie specjalizacje z zachowaniem unique constrainta, to musiałbyś np przy zapisie wyszukiwać specjalizację po nazwie (dodać metodę findByDescription w SpecializationRepository) i ustawić ją jako pole w doktorze, a jeśli takowej nie ma - dodać nową. Można też w jakiś inny sposób to zrobić, byle zagwarantować, że dodajemy nową specjalizację tylko wtedy gdy nie istnieje specjalizacja o danej nazwie.

A co do edycji doktorów to ok, na razie możemy to sobie darować ;) ale myślę, że i tak kiedyś to trzeba będzie zrobić (mogę to kiedyś przy okazji ogarnąć).

2017-07-22 23:21 UTC, zalon525 commented
Podsumowując musimy wybrać jedną z opcji:
- osobne API do dodawania specjalizacji (np przez POST /specializations), a w DoctorDTO musi być ustawiony poprawny klucz specjalizacji
- automatyczne wykrywanie specjalizacji w DoctorDTO po nazwie i tworzenie specjalizacji w razie potrzeby z zachowaniem unique constraint
- specjalizacja jako String

2017-07-24 15:09 UTC, WojciechKarpiel commented
Jest już git- jeśli doktor ma znaną już specjalizacje to otrzymuje istniejące ID specjalizacji

2017-07-25 14:16 UTC, merged